package awscatalog

// DefaultAWSServices 預設 AWS 服務列表
var DefaultAWSServices = []*AWSService{
	// Compute Services
	{
		ID:          "ec2",
		Name:        "Amazon EC2",
		Category:    "compute",
		Description: "可調整大小的雲端運算容量，提供虛擬伺服器",
		UseCases:    []string{"Web 應用程式", "批次處理", "開發測試環境", "高效能運算"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.0116,
			Unit:      "hour",
			FreeTier:  "每月 750 小時 t2.micro",
		},
		SAAExamTopics: []string{"EC2 執行個體類型", "Auto Scaling", "彈性 IP", "安全群組"},
		BestPractices: []string{"使用 Auto Scaling 自動調整容量", "選擇適當的執行個體類型", "使用 Reserved Instances 節省成本"},
	},
	{
		ID:          "lambda",
		Name:        "AWS Lambda",
		Category:    "compute",
		Description: "無伺服器運算服務，按需執行程式碼",
		UseCases:    []string{"事件驅動處理", "API 後端", "資料處理", "自動化任務"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.0000166667,
			Unit:      "GB-second",
			FreeTier:  "每月 100 萬次請求",
		},
		SAAExamTopics: []string{"無伺服器架構", "Lambda 觸發器", "並行執行", "冷啟動"},
		BestPractices: []string{"最小化函數大小", "使用環境變數", "設定適當的記憶體和逾時"},
	},
	{
		ID:          "ecs",
		Name:        "Amazon ECS",
		Category:    "compute",
		Description: "高度可擴展的容器管理服務",
		UseCases:    []string{"微服務架構", "批次處理", "CI/CD", "混合部署"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0,
			Unit:      "hour",
			FreeTier:  "ECS 本身免費，僅收取底層資源費用",
		},
		SAAExamTopics: []string{"容器化", "任務定義", "服務發現", "Fargate vs EC2"},
		BestPractices: []string{"使用 Fargate 簡化管理", "實作健康檢查", "使用 ECR 儲存映像"},
	},
	{
		ID:          "fargate",
		Name:        "AWS Fargate",
		Category:    "compute",
		Description: "無伺服器容器運算引擎",
		UseCases:    []string{"容器化應用", "微服務", "批次處理"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.04048,
			Unit:      "vCPU-hour",
			FreeTier:  "無",
		},
		SAAExamTopics: []string{"無伺服器容器", "ECS/EKS 整合", "資源配置"},
		BestPractices: []string{"適當設定 CPU 和記憶體", "使用 Spot 容量節省成本"},
	},

	// Storage Services
	{
		ID:          "s3",
		Name:        "Amazon S3",
		Category:    "storage",
		Description: "可擴展的物件儲存服務",
		UseCases:    []string{"靜態網站託管", "備份與還原", "資料湖", "內容分發"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.023,
			Unit:      "GB-month",
			FreeTier:  "每月 5 GB 標準儲存",
		},
		SAAExamTopics: []string{"S3 儲存類別", "生命週期政策", "版本控制", "跨區域複寫"},
		BestPractices: []string{"使用適當的儲存類別", "啟用版本控制", "設定生命週期政策"},
	},
	{
		ID:          "ebs",
		Name:        "Amazon EBS",
		Category:    "storage",
		Description: "EC2 執行個體的區塊儲存",
		UseCases:    []string{"資料庫儲存", "檔案系統", "開機磁碟區"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.10,
			Unit:      "GB-month",
			FreeTier:  "每月 30 GB SSD",
		},
		SAAExamTopics: []string{"EBS 磁碟區類型", "快照", "加密", "IOPS"},
		BestPractices: []string{"選擇適當的磁碟區類型", "定期建立快照", "啟用加密"},
	},
	{
		ID:          "efs",
		Name:        "Amazon EFS",
		Category:    "storage",
		Description: "彈性檔案系統，支援 NFS",
		UseCases:    []string{"共享檔案儲存", "內容管理", "Web 服務"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.30,
			Unit:      "GB-month",
			FreeTier:  "每月 5 GB",
		},
		SAAExamTopics: []string{"NFS 協定", "效能模式", "儲存類別", "跨 AZ 存取"},
		BestPractices: []string{"使用 Infrequent Access 儲存類別節省成本", "設定適當的效能模式"},
	},
	{
		ID:          "glacier",
		Name:        "Amazon S3 Glacier",
		Category:    "storage",
		Description: "低成本長期封存儲存",
		UseCases:    []string{"資料封存", "合規性保留", "備份"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.004,
			Unit:      "GB-month",
			FreeTier:  "無",
		},
		SAAExamTopics: []string{"擷取選項", "Vault Lock", "生命週期轉換"},
		BestPractices: []string{"用於不常存取的資料", "了解擷取時間和成本"},
	},

	// Database Services
	{
		ID:          "rds",
		Name:        "Amazon RDS",
		Category:    "database",
		Description: "受管關聯式資料庫服務",
		UseCases:    []string{"Web 應用程式", "企業應用", "電子商務"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.017,
			Unit:      "hour",
			FreeTier:  "每月 750 小時 db.t2.micro",
		},
		SAAExamTopics: []string{"Multi-AZ 部署", "讀取複本", "自動備份", "資料庫引擎"},
		BestPractices: []string{"使用 Multi-AZ 提高可用性", "設定自動備份", "使用讀取複本分散負載"},
	},
	{
		ID:          "dynamodb",
		Name:        "Amazon DynamoDB",
		Category:    "database",
		Description: "全受管 NoSQL 資料庫",
		UseCases:    []string{"遊戲", "IoT", "行動應用", "即時分析"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 1.25,
			Unit:      "million WCU",
			FreeTier:  "每月 25 GB 儲存",
		},
		SAAExamTopics: []string{"分區鍵設計", "全域資料表", "DAX 快取", "串流"},
		BestPractices: []string{"設計良好的分區鍵", "使用 DAX 加速讀取", "啟用 Point-in-time Recovery"},
	},
	{
		ID:          "aurora",
		Name:        "Amazon Aurora",
		Category:    "database",
		Description: "高效能受管關聯式資料庫",
		UseCases:    []string{"企業應用", "SaaS 應用", "高流量網站"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.10,
			Unit:      "hour",
			FreeTier:  "無",
		},
		SAAExamTopics: []string{"Aurora 複本", "全域資料庫", "Serverless", "故障轉移"},
		BestPractices: []string{"使用 Aurora Serverless 處理變動負載", "設定跨區域複本"},
	},
	{
		ID:          "elasticache",
		Name:        "Amazon ElastiCache",
		Category:    "database",
		Description: "受管記憶體快取服務",
		UseCases:    []string{"Session 管理", "資料庫快取", "即時分析"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.017,
			Unit:      "hour",
			FreeTier:  "無",
		},
		SAAExamTopics: []string{"Redis vs Memcached", "叢集模式", "複寫"},
		BestPractices: []string{"選擇適當的引擎", "設定適當的節點類型"},
	},

	// Networking Services
	{
		ID:          "vpc",
		Name:        "Amazon VPC",
		Category:    "networking",
		Description: "虛擬私有雲網路",
		UseCases:    []string{"網路隔離", "混合雲連接", "安全架構"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0,
			Unit:      "hour",
			FreeTier:  "VPC 本身免費",
		},
		SAAExamTopics: []string{"子網路", "路由表", "NAT Gateway", "VPC Peering"},
		BestPractices: []string{"使用多個 AZ", "設定適當的 CIDR", "使用安全群組和 NACL"},
	},
	{
		ID:          "cloudfront",
		Name:        "Amazon CloudFront",
		Category:    "networking",
		Description: "全球內容傳遞網路 (CDN)",
		UseCases:    []string{"靜態內容加速", "動態內容加速", "串流媒體"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.085,
			Unit:      "GB",
			FreeTier:  "每月 1 TB 資料傳輸",
		},
		SAAExamTopics: []string{"邊緣位置", "Origin", "快取行為", "SSL/TLS"},
		BestPractices: []string{"設定適當的 TTL", "使用 Origin Shield", "啟用壓縮"},
	},
	{
		ID:          "route53",
		Name:        "Amazon Route 53",
		Category:    "networking",
		Description: "可擴展的 DNS 服務",
		UseCases:    []string{"網域註冊", "DNS 路由", "健康檢查"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.50,
			Unit:      "hosted zone/month",
			FreeTier:  "無",
		},
		SAAExamTopics: []string{"路由政策", "健康檢查", "Alias 記錄", "故障轉移"},
		BestPractices: []string{"使用 Alias 記錄指向 AWS 資源", "設定健康檢查"},
	},
	{
		ID:          "elb",
		Name:        "Elastic Load Balancing",
		Category:    "networking",
		Description: "自動分散流量的負載平衡器",
		UseCases:    []string{"高可用性", "自動擴展", "SSL 終止"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.0225,
			Unit:      "hour",
			FreeTier:  "每月 750 小時",
		},
		SAAExamTopics: []string{"ALB vs NLB vs CLB", "目標群組", "健康檢查", "跨區域負載平衡"},
		BestPractices: []string{"選擇適當的負載平衡器類型", "設定健康檢查", "使用 SSL/TLS"},
	},
	{
		ID:          "apigateway",
		Name:        "Amazon API Gateway",
		Category:    "networking",
		Description: "建立、發布和管理 API",
		UseCases:    []string{"REST API", "WebSocket API", "微服務閘道"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 3.50,
			Unit:      "million requests",
			FreeTier:  "每月 100 萬次 REST API 呼叫",
		},
		SAAExamTopics: []string{"REST vs HTTP API", "授權", "節流", "快取"},
		BestPractices: []string{"使用 HTTP API 節省成本", "設定適當的節流限制"},
	},

	// Security Services
	{
		ID:          "iam",
		Name:        "AWS IAM",
		Category:    "security",
		Description: "身分和存取管理",
		UseCases:    []string{"使用者管理", "權限控制", "聯合身分"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0,
			Unit:      "free",
			FreeTier:  "完全免費",
		},
		SAAExamTopics: []string{"IAM 政策", "角色", "MFA", "最小權限原則"},
		BestPractices: []string{"使用角色而非長期憑證", "啟用 MFA", "遵循最小權限原則"},
	},
	{
		ID:          "waf",
		Name:        "AWS WAF",
		Category:    "security",
		Description: "Web 應用程式防火牆",
		UseCases:    []string{"SQL 注入防護", "XSS 防護", "DDoS 緩解"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 5.00,
			Unit:      "web ACL/month",
			FreeTier:  "無",
		},
		SAAExamTopics: []string{"規則群組", "受管規則", "速率限制"},
		BestPractices: []string{"使用受管規則", "設定速率限制", "監控和調整規則"},
	},
	{
		ID:          "shield",
		Name:        "AWS Shield",
		Category:    "security",
		Description: "DDoS 防護服務",
		UseCases:    []string{"DDoS 防護", "應用程式保護"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0,
			Unit:      "free",
			FreeTier:  "Shield Standard 免費",
		},
		SAAExamTopics: []string{"Shield Standard vs Advanced", "DDoS 緩解"},
		BestPractices: []string{"所有 AWS 資源自動受 Shield Standard 保護"},
	},
	{
		ID:          "kms",
		Name:        "AWS KMS",
		Category:    "security",
		Description: "金鑰管理服務",
		UseCases:    []string{"資料加密", "金鑰輪換", "合規性"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 1.00,
			Unit:      "key/month",
			FreeTier:  "AWS 受管金鑰免費",
		},
		SAAExamTopics: []string{"CMK", "金鑰政策", "加密類型", "金鑰輪換"},
		BestPractices: []string{"使用 CMK 進行細粒度控制", "啟用自動金鑰輪換"},
	},
	{
		ID:          "guardduty",
		Name:        "Amazon GuardDuty",
		Category:    "security",
		Description: "智慧威脅偵測服務",
		UseCases:    []string{"威脅偵測", "異常行為分析", "合規性"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 4.00,
			Unit:      "million events",
			FreeTier:  "30 天免費試用",
		},
		SAAExamTopics: []string{"威脅偵測", "發現類型", "整合"},
		BestPractices: []string{"在所有區域啟用", "整合 Security Hub"},
	},
	{
		ID:          "securityhub",
		Name:        "AWS Security Hub",
		Category:    "security",
		Description: "安全狀態管理服務",
		UseCases:    []string{"安全合規", "集中管理", "自動化修復"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.0010,
			Unit:      "check",
			FreeTier:  "30 天免費試用",
		},
		SAAExamTopics: []string{"安全標準", "發現彙總", "自動化"},
		BestPractices: []string{"啟用自動化修復", "整合其他安全服務"},
	},

	// Analytics Services
	{
		ID:          "athena",
		Name:        "Amazon Athena",
		Category:    "analytics",
		Description: "無伺服器互動式查詢服務",
		UseCases:    []string{"日誌分析", "資料湖查詢", "臨時分析"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 5.00,
			Unit:      "TB scanned",
			FreeTier:  "無",
		},
		SAAExamTopics: []string{"S3 查詢", "Glue 整合", "分區"},
		BestPractices: []string{"使用分區減少掃描量", "使用 Parquet 格式"},
	},
	{
		ID:          "kinesis",
		Name:        "Amazon Kinesis",
		Category:    "analytics",
		Description: "即時資料串流服務",
		UseCases:    []string{"即時分析", "日誌處理", "IoT 資料"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.015,
			Unit:      "shard hour",
			FreeTier:  "無",
		},
		SAAExamTopics: []string{"Data Streams", "Firehose", "Analytics", "分片"},
		BestPractices: []string{"適當設定分片數量", "使用 Firehose 簡化資料載入"},
	},
	{
		ID:          "redshift",
		Name:        "Amazon Redshift",
		Category:    "analytics",
		Description: "雲端資料倉儲",
		UseCases:    []string{"商業智慧", "資料分析", "報表"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.25,
			Unit:      "hour",
			FreeTier:  "2 個月免費試用",
		},
		SAAExamTopics: []string{"叢集架構", "Spectrum", "並行擴展", "快照"},
		BestPractices: []string{"使用 Spectrum 查詢 S3 資料", "設定適當的節點類型"},
	},

	// Management Services
	{
		ID:          "cloudwatch",
		Name:        "Amazon CloudWatch",
		Category:    "management",
		Description: "監控和可觀測性服務",
		UseCases:    []string{"指標監控", "日誌管理", "警報"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.30,
			Unit:      "metric/month",
			FreeTier:  "10 個自訂指標",
		},
		SAAExamTopics: []string{"指標", "日誌", "警報", "儀表板"},
		BestPractices: []string{"設定適當的警報閾值", "使用日誌洞察分析日誌"},
	},
	{
		ID:          "cloudtrail",
		Name:        "AWS CloudTrail",
		Category:    "management",
		Description: "API 活動追蹤服務",
		UseCases:    []string{"稽核", "合規性", "安全分析"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 2.00,
			Unit:      "100,000 events",
			FreeTier:  "管理事件免費",
		},
		SAAExamTopics: []string{"追蹤", "事件類型", "S3 整合", "組織追蹤"},
		BestPractices: []string{"在所有區域啟用", "將日誌傳送到 S3"},
	},
	{
		ID:          "config",
		Name:        "AWS Config",
		Category:    "management",
		Description: "資源組態追蹤服務",
		UseCases:    []string{"合規性稽核", "組態管理", "變更追蹤"},
		PricingModel: PricingModel{
			Type:      "on_demand",
			BasePrice: 0.003,
			Unit:      "configuration item",
			FreeTier:  "無",
		},
		SAAExamTopics: []string{"規則", "合規性", "修復動作"},
		BestPractices: []string{"使用受管規則", "設定自動修復"},
	},
}

// GetDefaultCatalog 取得預設服務目錄
func GetDefaultCatalog() AWSServiceCatalog {
	return NewAWSServiceCatalogWithServices(DefaultAWSServices)
}
