package event

// DefaultEvents 預設事件資料集 (50+ 事件)
// 涵蓋: 擴廠、跨國合作、資安事件、資料外洩、系統故障、業務成長、法規遵循等真實情境
var DefaultEvents = []*Event{
	// ==================== 機會事件 (Opportunity) ====================
	{
		ID:           "opp-001",
		Type:         EventOpportunity,
		Title:        "擴廠機會",
		Description:  "公司業務成長迅速，需要擴展基礎設施以應對增加的流量",
		RealWorldRef: "Netflix 2016年全球擴展案例",
		Context: EventContext{
			Scenario:       "業務量在過去三個月成長了200%，現有伺服器已達到80%負載",
			BusinessImpact: "若不擴展，可能導致服務中斷，影響客戶體驗",
			TechnicalNeeds: []string{"擴展運算能力", "增加儲存空間", "提升網路頻寬"},
			Constraints:    []string{"預算有限", "需在一個月內完成"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS Auto Scaling",
				Description:  "部署 Auto Scaling 群組，根據負載自動調整 EC2 實例數量",
				IsAWS:        true,
				AWSServices:  []string{"EC2", "Auto Scaling", "ELB"},
				Requirements: ChoiceRequirements{MinCapital: 200, MinEmployees: 5, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 300, EmployeeChange: 5, SecurityChange: 0, CloudAdoptionChange: 10, SuccessRate: 0.85, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "購買實體伺服器",
				Description:    "採購新的實體伺服器並部署在自有機房",
				IsAWS:          false,
				OnPremSolution: "購買 Dell PowerEdge 伺服器",
				Requirements:   ChoiceRequirements{MinCapital: 500, MinEmployees: 10, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 150, EmployeeChange: 2, SecurityChange: 0, CloudAdoptionChange: -5, SuccessRate: 0.7, TimeToImplement: 3},
			},
		},
		AWSTopics: []string{"EC2", "Auto Scaling", "Elastic Load Balancing", "高可用性架構"},
	},
	{
		ID:           "opp-002",
		Type:         EventOpportunity,
		Title:        "跨國市場拓展",
		Description:  "公司計劃進軍東南亞市場，需要在當地建立服務據點",
		RealWorldRef: "Grab 東南亞擴展策略",
		Context: EventContext{
			Scenario:       "東南亞市場需求強勁，需要低延遲的服務體驗",
			BusinessImpact: "成功進入可帶來30%營收成長",
			TechnicalNeeds: []string{"多區域部署", "內容分發", "資料合規"},
			Constraints:    []string{"需符合當地資料法規", "預算控制在500萬以內"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 全球基礎設施",
				Description:  "利用 AWS 新加坡區域和 CloudFront 建立全球服務",
				IsAWS:        true,
				AWSServices:  []string{"CloudFront", "Route 53", "S3", "EC2"},
				Requirements: ChoiceRequirements{MinCapital: 300, MinEmployees: 10, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 500, EmployeeChange: 15, SecurityChange: 1, CloudAdoptionChange: 15, SuccessRate: 0.8, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "與當地 IDC 合作",
				Description:    "租用當地資料中心空間，自行部署伺服器",
				IsAWS:          false,
				OnPremSolution: "租用新加坡 Equinix 機房",
				Requirements:   ChoiceRequirements{MinCapital: 800, MinEmployees: 20, MinSecurityLevel: 3},
				Outcomes:       ChoiceOutcomes{CapitalChange: 300, EmployeeChange: 8, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.6, TimeToImplement: 4},
			},
		},
		AWSTopics: []string{"CloudFront", "Route 53", "多區域架構", "全球加速"},
	},
	{
		ID:           "opp-003",
		Type:         EventOpportunity,
		Title:        "大型企業合作案",
		Description:  "知名企業希望與貴公司合作，但要求通過 SOC 2 認證",
		RealWorldRef: "SaaS 企業合規要求",
		Context: EventContext{
			Scenario:       "潛在客戶為財星500大企業，年度合約價值1000萬",
			BusinessImpact: "取得認證可開啟企業市場大門",
			TechnicalNeeds: []string{"安全合規", "稽核日誌", "存取控制"},
			Constraints:    []string{"需在6個月內取得認證"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 合規服務",
				Description:  "利用 AWS Artifact、CloudTrail、Config 快速達成合規",
				IsAWS:        true,
				AWSServices:  []string{"AWS Artifact", "CloudTrail", "AWS Config", "Security Hub"},
				Requirements: ChoiceRequirements{MinCapital: 100, MinEmployees: 5, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 800, EmployeeChange: 10, SecurityChange: 2, CloudAdoptionChange: 20, SuccessRate: 0.9, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "自建合規系統",
				Description:    "聘請顧問公司協助建立內部合規系統",
				IsAWS:          false,
				OnPremSolution: "聘請四大會計師事務所顧問",
				Requirements:   ChoiceRequirements{MinCapital: 500, MinEmployees: 15, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 600, EmployeeChange: 5, SecurityChange: 1, CloudAdoptionChange: 0, SuccessRate: 0.7, TimeToImplement: 4},
			},
		},
		AWSTopics: []string{"AWS Artifact", "CloudTrail", "AWS Config", "合規性", "SOC 2"},
	},
	{
		ID:           "opp-004",
		Type:         EventOpportunity,
		Title:        "AI/ML 產品開發",
		Description:  "市場對 AI 功能需求增加，公司決定開發機器學習產品",
		RealWorldRef: "OpenAI GPT 產品化案例",
		Context: EventContext{
			Scenario:       "競爭對手已推出 AI 功能，客戶詢問度增加",
			BusinessImpact: "成功開發可提升產品競爭力",
			TechnicalNeeds: []string{"機器學習平台", "GPU 運算", "資料處理"},
			Constraints:    []string{"團隊缺乏 ML 經驗", "需快速上市"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS SageMaker",
				Description:  "利用 SageMaker 快速建立、訓練和部署 ML 模型",
				IsAWS:        true,
				AWSServices:  []string{"SageMaker", "S3", "Lambda"},
				Requirements: ChoiceRequirements{MinCapital: 300, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 600, EmployeeChange: 8, SecurityChange: 0, CloudAdoptionChange: 25, SuccessRate: 0.75, TimeToImplement: 3},
			},
			{
				ID:             2,
				Title:          "自建 ML 基礎設施",
				Description:    "購買 GPU 伺服器，自行建立訓練環境",
				IsAWS:          false,
				OnPremSolution: "購買 NVIDIA DGX 工作站",
				Requirements:   ChoiceRequirements{MinCapital: 1000, MinEmployees: 15, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 400, EmployeeChange: 5, SecurityChange: 0, CloudAdoptionChange: -10, SuccessRate: 0.5, TimeToImplement: 6},
			},
		},
		AWSTopics: []string{"SageMaker", "機器學習", "深度學習", "模型部署"},
	},
	{
		ID:           "opp-005",
		Type:         EventOpportunity,
		Title:        "行動應用程式開發",
		Description:  "公司決定開發行動應用程式以擴大用戶群",
		RealWorldRef: "Uber 行動優先策略",
		Context: EventContext{
			Scenario:       "行動用戶佔比已達60%，需要原生應用體驗",
			BusinessImpact: "可提升用戶黏著度和轉換率",
			TechnicalNeeds: []string{"行動後端", "推播通知", "用戶認證"},
			Constraints:    []string{"需支援 iOS 和 Android", "預算有限"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS Amplify",
				Description:  "利用 Amplify 快速建立行動應用後端",
				IsAWS:        true,
				AWSServices:  []string{"Amplify", "Cognito", "AppSync", "SNS"},
				Requirements: ChoiceRequirements{MinCapital: 150, MinEmployees: 5, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 400, EmployeeChange: 6, SecurityChange: 1, CloudAdoptionChange: 15, SuccessRate: 0.85, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "自建後端服務",
				Description:    "使用開源框架自行開發後端 API",
				IsAWS:          false,
				OnPremSolution: "使用 Node.js + MongoDB 自建",
				Requirements:   ChoiceRequirements{MinCapital: 200, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 300, EmployeeChange: 4, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.7, TimeToImplement: 4},
			},
		},
		AWSTopics: []string{"Amplify", "Cognito", "AppSync", "行動開發"},
	},
	{
		ID:           "opp-006",
		Type:         EventOpportunity,
		Title:        "電商平台升級",
		Description:  "雙11購物節即將到來，需要升級系統以應對流量高峰",
		RealWorldRef: "阿里巴巴雙11技術架構",
		Context: EventContext{
			Scenario:       "預計流量將是平時的10倍，需要彈性擴展能力",
			BusinessImpact: "成功應對可帶來年度最大營收",
			TechnicalNeeds: []string{"彈性擴展", "快取優化", "資料庫效能"},
			Constraints:    []string{"只有2週準備時間", "不能影響現有服務"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 彈性架構",
				Description:  "部署 ElastiCache、Auto Scaling 和 RDS Read Replica",
				IsAWS:        true,
				AWSServices:  []string{"ElastiCache", "Auto Scaling", "RDS", "CloudFront"},
				Requirements: ChoiceRequirements{MinCapital: 250, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 700, EmployeeChange: 5, SecurityChange: 0, CloudAdoptionChange: 20, SuccessRate: 0.9, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "增加實體伺服器",
				Description:    "臨時租用額外伺服器應對高峰",
				IsAWS:          false,
				OnPremSolution: "租用 IDC 臨時伺服器",
				Requirements:   ChoiceRequirements{MinCapital: 400, MinEmployees: 12, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 500, EmployeeChange: 2, SecurityChange: 0, CloudAdoptionChange: -5, SuccessRate: 0.6, TimeToImplement: 2},
			},
		},
		AWSTopics: []string{"ElastiCache", "Auto Scaling", "RDS", "高可用性"},
	},
	{
		ID:           "opp-007",
		Type:         EventOpportunity,
		Title:        "物聯網產品線",
		Description:  "公司決定進入 IoT 市場，開發智慧裝置產品",
		RealWorldRef: "小米 IoT 生態系統",
		Context: EventContext{
			Scenario:       "IoT 市場快速成長，客戶詢問智慧解決方案",
			BusinessImpact: "可開拓新的營收來源",
			TechnicalNeeds: []string{"裝置管理", "資料收集", "即時分析"},
			Constraints:    []string{"需支援大量裝置連接", "低延遲要求"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS IoT Core",
				Description:  "利用 AWS IoT 服務建立完整 IoT 平台",
				IsAWS:        true,
				AWSServices:  []string{"IoT Core", "IoT Analytics", "Kinesis", "Lambda"},
				Requirements: ChoiceRequirements{MinCapital: 400, MinEmployees: 10, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 600, EmployeeChange: 12, SecurityChange: 1, CloudAdoptionChange: 25, SuccessRate: 0.8, TimeToImplement: 3},
			},
			{
				ID:             2,
				Title:          "自建 IoT 平台",
				Description:    "使用開源方案如 ThingsBoard 自建平台",
				IsAWS:          false,
				OnPremSolution: "部署 ThingsBoard + MQTT Broker",
				Requirements:   ChoiceRequirements{MinCapital: 600, MinEmployees: 15, MinSecurityLevel: 3},
				Outcomes:       ChoiceOutcomes{CapitalChange: 400, EmployeeChange: 8, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.6, TimeToImplement: 5},
			},
		},
		AWSTopics: []string{"IoT Core", "IoT Analytics", "Kinesis", "物聯網架構"},
	},
	{
		ID:           "opp-008",
		Type:         EventOpportunity,
		Title:        "資料分析平台",
		Description:  "公司需要建立資料分析平台以支援商業決策",
		RealWorldRef: "Airbnb 資料平台案例",
		Context: EventContext{
			Scenario:       "資料量快速成長，現有工具無法滿足分析需求",
			BusinessImpact: "數據驅動決策可提升營運效率",
			TechnicalNeeds: []string{"資料倉儲", "ETL 流程", "視覺化報表"},
			Constraints:    []string{"需整合多個資料來源", "分析師缺乏技術背景"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 資料分析服務",
				Description:  "建立 Redshift + Glue + QuickSight 資料平台",
				IsAWS:        true,
				AWSServices:  []string{"Redshift", "Glue", "QuickSight", "Athena"},
				Requirements: ChoiceRequirements{MinCapital: 300, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 500, EmployeeChange: 6, SecurityChange: 0, CloudAdoptionChange: 20, SuccessRate: 0.85, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "自建 Hadoop 叢集",
				Description:    "部署 Hadoop + Spark 叢集進行大數據分析",
				IsAWS:          false,
				OnPremSolution: "建立 Cloudera Hadoop 叢集",
				Requirements:   ChoiceRequirements{MinCapital: 800, MinEmployees: 15, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 350, EmployeeChange: 4, SecurityChange: 0, CloudAdoptionChange: -5, SuccessRate: 0.6, TimeToImplement: 5},
			},
		},
		AWSTopics: []string{"Redshift", "Glue", "QuickSight", "Athena", "資料分析"},
	},
	{
		ID:           "opp-009",
		Type:         EventOpportunity,
		Title:        "微服務架構轉型",
		Description:  "單體應用程式難以維護，需要轉型為微服務架構",
		RealWorldRef: "Amazon 微服務轉型歷程",
		Context: EventContext{
			Scenario:       "部署週期長達數週，團隊協作困難",
			BusinessImpact: "轉型成功可加速產品迭代",
			TechnicalNeeds: []string{"容器化", "服務編排", "API 閘道"},
			Constraints:    []string{"不能中斷現有服務", "團隊需要培訓"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 容器服務",
				Description:  "採用 ECS/EKS + API Gateway 建立微服務架構",
				IsAWS:        true,
				AWSServices:  []string{"ECS", "EKS", "API Gateway", "ECR"},
				Requirements: ChoiceRequirements{MinCapital: 350, MinEmployees: 12, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 450, EmployeeChange: 8, SecurityChange: 1, CloudAdoptionChange: 30, SuccessRate: 0.75, TimeToImplement: 4},
			},
			{
				ID:             2,
				Title:          "自建 Kubernetes 叢集",
				Description:    "在自有機房部署 Kubernetes 叢集",
				IsAWS:          false,
				OnPremSolution: "部署 Rancher + Kubernetes",
				Requirements:   ChoiceRequirements{MinCapital: 600, MinEmployees: 18, MinSecurityLevel: 3},
				Outcomes:       ChoiceOutcomes{CapitalChange: 300, EmployeeChange: 5, SecurityChange: 0, CloudAdoptionChange: 5, SuccessRate: 0.55, TimeToImplement: 6},
			},
		},
		AWSTopics: []string{"ECS", "EKS", "API Gateway", "微服務", "容器"},
	},
	{
		ID:           "opp-010",
		Type:         EventOpportunity,
		Title:        "災難復原計畫",
		Description:  "董事會要求建立完整的災難復原計畫",
		RealWorldRef: "金融業 DR 要求",
		Context: EventContext{
			Scenario:       "監管機構要求 RTO < 4小時，RPO < 1小時",
			BusinessImpact: "符合要求可維持營業執照",
			TechnicalNeeds: []string{"跨區域備份", "自動故障轉移", "資料同步"},
			Constraints:    []string{"預算有限", "需定期演練"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 災難復原服務",
				Description:  "利用 AWS Backup、Route 53 健康檢查建立 DR 方案",
				IsAWS:        true,
				AWSServices:  []string{"AWS Backup", "Route 53", "S3 Cross-Region Replication", "RDS Multi-AZ"},
				Requirements: ChoiceRequirements{MinCapital: 200, MinEmployees: 6, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 300, EmployeeChange: 3, SecurityChange: 2, CloudAdoptionChange: 15, SuccessRate: 0.9, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "建立異地備援機房",
				Description:    "在不同地點建立備援資料中心",
				IsAWS:          false,
				OnPremSolution: "租用異地 IDC 建立備援",
				Requirements:   ChoiceRequirements{MinCapital: 1000, MinEmployees: 15, MinSecurityLevel: 3},
				Outcomes:       ChoiceOutcomes{CapitalChange: 200, EmployeeChange: 2, SecurityChange: 1, CloudAdoptionChange: -5, SuccessRate: 0.7, TimeToImplement: 6},
			},
		},
		AWSTopics: []string{"AWS Backup", "Route 53", "災難復原", "高可用性", "RTO/RPO"},
	},

	// ==================== 命運事件 (Fate) ====================
	{
		ID:           "fate-001",
		Type:         EventFate,
		Title:        "市場景氣變化",
		Description:  "全球經濟衰退，客戶縮減 IT 預算",
		RealWorldRef: "2008 金融危機影響",
		Context: EventContext{
			Scenario:       "多個大客戶通知將縮減合約規模",
			BusinessImpact: "營收可能下降20-30%",
			TechnicalNeeds: []string{"成本優化", "資源整合"},
			Constraints:    []string{"不能裁員", "需維持服務品質"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "優化雲端成本",
				Description:  "使用 AWS Cost Explorer 和 Savings Plans 優化支出",
				IsAWS:        true,
				AWSServices:  []string{"Cost Explorer", "Savings Plans", "Trusted Advisor"},
				Requirements: ChoiceRequirements{MinCapital: 50, MinEmployees: 3, MinSecurityLevel: 1},
				Outcomes:     ChoiceOutcomes{CapitalChange: 100, EmployeeChange: 0, SecurityChange: 0, CloudAdoptionChange: 5, SuccessRate: 0.85, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "縮減基礎設施",
				Description:    "關閉部分伺服器，整合服務",
				IsAWS:          false,
				OnPremSolution: "整合實體伺服器",
				Requirements:   ChoiceRequirements{MinCapital: 100, MinEmployees: 5, MinSecurityLevel: 1},
				Outcomes:       ChoiceOutcomes{CapitalChange: 50, EmployeeChange: -2, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.7, TimeToImplement: 2},
			},
		},
		AWSTopics: []string{"Cost Explorer", "Savings Plans", "成本優化"},
	},
	{
		ID:           "fate-002",
		Type:         EventFate,
		Title:        "關鍵人才離職",
		Description:  "核心技術人員被競爭對手挖角",
		RealWorldRef: "科技業人才競爭",
		Context: EventContext{
			Scenario:       "負責核心系統的資深工程師提出離職",
			BusinessImpact: "可能影響專案進度和系統維護",
			TechnicalNeeds: []string{"知識轉移", "文件化", "自動化"},
			Constraints:    []string{"交接時間只有2週", "需維持系統穩定"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "導入 AWS 託管服務",
				Description:  "將自建服務遷移到 AWS 託管服務，降低維護負擔",
				IsAWS:        true,
				AWSServices:  []string{"RDS", "ElastiCache", "OpenSearch"},
				Requirements: ChoiceRequirements{MinCapital: 200, MinEmployees: 5, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 50, EmployeeChange: 0, SecurityChange: 0, CloudAdoptionChange: 15, SuccessRate: 0.8, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "緊急招募替代人選",
				Description:    "透過獵頭公司緊急招募",
				IsAWS:          false,
				OnPremSolution: "支付高額獵頭費用",
				Requirements:   ChoiceRequirements{MinCapital: 300, MinEmployees: 3, MinSecurityLevel: 1},
				Outcomes:       ChoiceOutcomes{CapitalChange: -100, EmployeeChange: 1, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.5, TimeToImplement: 3},
			},
		},
		AWSTopics: []string{"託管服務", "RDS", "運維自動化"},
	},
	{
		ID:           "fate-003",
		Type:         EventFate,
		Title:        "供應商漲價",
		Description:  "主要軟體供應商宣布大幅調漲授權費用",
		RealWorldRef: "Oracle 授權費調整",
		Context: EventContext{
			Scenario:       "資料庫授權費用將上漲50%",
			BusinessImpact: "IT 成本大幅增加",
			TechnicalNeeds: []string{"資料庫遷移", "相容性測試"},
			Constraints:    []string{"需在授權到期前完成", "不能影響業務"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "遷移到 AWS 資料庫",
				Description:  "使用 AWS DMS 遷移到 Aurora 或 RDS",
				IsAWS:        true,
				AWSServices:  []string{"Aurora", "RDS", "DMS"},
				Requirements: ChoiceRequirements{MinCapital: 250, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 200, EmployeeChange: 2, SecurityChange: 0, CloudAdoptionChange: 25, SuccessRate: 0.75, TimeToImplement: 3},
			},
			{
				ID:             2,
				Title:          "續約並談判",
				Description:    "與供應商談判爭取較低漲幅",
				IsAWS:          false,
				OnPremSolution: "簽訂多年合約換取折扣",
				Requirements:   ChoiceRequirements{MinCapital: 400, MinEmployees: 3, MinSecurityLevel: 1},
				Outcomes:       ChoiceOutcomes{CapitalChange: -50, EmployeeChange: 0, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.6, TimeToImplement: 1},
			},
		},
		AWSTopics: []string{"Aurora", "RDS", "DMS", "資料庫遷移"},
	},
	{
		ID:           "fate-004",
		Type:         EventFate,
		Title:        "法規變更",
		Description:  "政府頒布新的資料保護法規",
		RealWorldRef: "GDPR 實施影響",
		Context: EventContext{
			Scenario:       "新法規要求資料必須在地儲存，並提供刪除機制",
			BusinessImpact: "不合規將面臨高額罰款",
			TechnicalNeeds: []string{"資料在地化", "資料生命週期管理", "稽核追蹤"},
			Constraints:    []string{"6個月內需合規", "需保留現有功能"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 合規工具",
				Description:  "利用 AWS 本地區域和資料管理服務達成合規",
				IsAWS:        true,
				AWSServices:  []string{"S3 Object Lock", "Macie", "CloudTrail", "AWS Config"},
				Requirements: ChoiceRequirements{MinCapital: 150, MinEmployees: 5, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 100, EmployeeChange: 2, SecurityChange: 2, CloudAdoptionChange: 10, SuccessRate: 0.85, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "建立本地資料中心",
				Description:    "在當地建立資料中心以符合法規",
				IsAWS:          false,
				OnPremSolution: "租用本地 IDC 空間",
				Requirements:   ChoiceRequirements{MinCapital: 500, MinEmployees: 10, MinSecurityLevel: 3},
				Outcomes:       ChoiceOutcomes{CapitalChange: -100, EmployeeChange: 3, SecurityChange: 1, CloudAdoptionChange: -10, SuccessRate: 0.7, TimeToImplement: 4},
			},
		},
		AWSTopics: []string{"資料合規", "Macie", "CloudTrail", "GDPR"},
	},
	{
		ID:           "fate-005",
		Type:         EventFate,
		Title:        "競爭對手併購",
		Description:  "主要競爭對手被大型企業併購，獲得大量資源",
		RealWorldRef: "科技業併購案例",
		Context: EventContext{
			Scenario:       "競爭對手獲得資金後開始降價搶市",
			BusinessImpact: "市場份額可能流失",
			TechnicalNeeds: []string{"加速創新", "提升效率", "降低成本"},
			Constraints:    []string{"資源有限", "需快速反應"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "加速雲端轉型",
				Description:  "全面採用 AWS 服務加速產品開發",
				IsAWS:        true,
				AWSServices:  []string{"Lambda", "Step Functions", "CodePipeline"},
				Requirements: ChoiceRequirements{MinCapital: 200, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 150, EmployeeChange: 5, SecurityChange: 0, CloudAdoptionChange: 20, SuccessRate: 0.75, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "專注利基市場",
				Description:    "放棄大眾市場，專注特定垂直領域",
				IsAWS:          false,
				OnPremSolution: "調整產品策略",
				Requirements:   ChoiceRequirements{MinCapital: 100, MinEmployees: 5, MinSecurityLevel: 1},
				Outcomes:       ChoiceOutcomes{CapitalChange: 100, EmployeeChange: -3, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.65, TimeToImplement: 3},
			},
		},
		AWSTopics: []string{"Lambda", "Step Functions", "DevOps", "敏捷開發"},
	},
	{
		ID:           "fate-006",
		Type:         EventFate,
		Title:        "自然災害",
		Description:  "颱風導致主要機房停電",
		RealWorldRef: "2011 泰國洪水影響",
		Context: EventContext{
			Scenario:       "機房預計停電48小時，備用電源只能維持8小時",
			BusinessImpact: "服務中斷將造成重大損失",
			TechnicalNeeds: []string{"故障轉移", "資料備份", "服務恢復"},
			Constraints:    []string{"時間緊迫", "需立即行動"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "啟動 AWS 災難復原",
				Description:  "將流量切換到 AWS 雲端備援環境",
				IsAWS:        true,
				AWSServices:  []string{"Route 53", "CloudFormation", "S3"},
				Requirements: ChoiceRequirements{MinCapital: 100, MinEmployees: 3, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 50, EmployeeChange: 0, SecurityChange: 0, CloudAdoptionChange: 15, SuccessRate: 0.9, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "等待電力恢復",
				Description:    "使用備用電源撐過停電期間",
				IsAWS:          false,
				OnPremSolution: "啟動柴油發電機",
				Requirements:   ChoiceRequirements{MinCapital: 50, MinEmployees: 2, MinSecurityLevel: 1},
				Outcomes:       ChoiceOutcomes{CapitalChange: -200, EmployeeChange: 0, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.4, TimeToImplement: 1},
			},
		},
		AWSTopics: []string{"災難復原", "Route 53", "高可用性"},
	},
	{
		ID:           "fate-007",
		Type:         EventFate,
		Title:        "技術債爆發",
		Description:  "長期累積的技術債導致系統不穩定",
		RealWorldRef: "技術債管理案例",
		Context: EventContext{
			Scenario:       "系統頻繁當機，每次修復都引發新問題",
			BusinessImpact: "客戶抱怨增加，團隊士氣低落",
			TechnicalNeeds: []string{"系統重構", "自動化測試", "監控告警"},
			Constraints:    []string{"不能停止新功能開發", "預算有限"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "漸進式雲端遷移",
				Description:  "逐步將問題模組遷移到 AWS 託管服務",
				IsAWS:        true,
				AWSServices:  []string{"Lambda", "RDS", "CloudWatch"},
				Requirements: ChoiceRequirements{MinCapital: 200, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 100, EmployeeChange: 2, SecurityChange: 1, CloudAdoptionChange: 20, SuccessRate: 0.8, TimeToImplement: 3},
			},
			{
				ID:             2,
				Title:          "全面重構",
				Description:    "暫停新功能，全力重構系統",
				IsAWS:          false,
				OnPremSolution: "投入全部工程資源重構",
				Requirements:   ChoiceRequirements{MinCapital: 300, MinEmployees: 12, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: -50, EmployeeChange: 0, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.6, TimeToImplement: 5},
			},
		},
		AWSTopics: []string{"Lambda", "CloudWatch", "系統現代化"},
	},
	{
		ID:           "fate-008",
		Type:         EventFate,
		Title:        "客戶流失",
		Description:  "重要客戶決定不續約",
		RealWorldRef: "B2B 客戶關係管理",
		Context: EventContext{
			Scenario:       "佔營收15%的大客戶通知不續約",
			BusinessImpact: "需要快速找到替代營收來源",
			TechnicalNeeds: []string{"產品改進", "新客戶開發", "成本控制"},
			Constraints:    []string{"3個月內需補足營收缺口"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "推出 SaaS 版本",
				Description:  "將產品轉型為 SaaS，開拓中小企業市場",
				IsAWS:        true,
				AWSServices:  []string{"ECS", "RDS", "CloudFront"},
				Requirements: ChoiceRequirements{MinCapital: 250, MinEmployees: 10, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 200, EmployeeChange: 5, SecurityChange: 0, CloudAdoptionChange: 25, SuccessRate: 0.7, TimeToImplement: 3},
			},
			{
				ID:             2,
				Title:          "加強業務開發",
				Description:    "增加業務人員，積極開發新客戶",
				IsAWS:          false,
				OnPremSolution: "擴大業務團隊",
				Requirements:   ChoiceRequirements{MinCapital: 200, MinEmployees: 5, MinSecurityLevel: 1},
				Outcomes:       ChoiceOutcomes{CapitalChange: 100, EmployeeChange: 8, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.55, TimeToImplement: 4},
			},
		},
		AWSTopics: []string{"SaaS 架構", "多租戶", "ECS"},
	},

	// ==================== 關卡事件 (Challenge) ====================
	{
		ID:           "challenge-001",
		Type:         EventChallenge,
		Title:        "效能瓶頸",
		Description:  "系統回應時間過長，用戶抱怨增加",
		RealWorldRef: "電商效能優化案例",
		Context: EventContext{
			Scenario:       "API 回應時間從 200ms 增加到 2 秒",
			BusinessImpact: "轉換率下降，用戶流失",
			TechnicalNeeds: []string{"效能分析", "快取優化", "資料庫調校"},
			Constraints:    []string{"不能更改 API 介面", "預算有限"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 效能優化服務",
				Description:  "部署 ElastiCache、CloudFront 和 X-Ray 進行優化",
				IsAWS:        true,
				AWSServices:  []string{"ElastiCache", "CloudFront", "X-Ray"},
				Requirements: ChoiceRequirements{MinCapital: 150, MinEmployees: 5, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 200, EmployeeChange: 2, SecurityChange: 0, CloudAdoptionChange: 15, SuccessRate: 0.85, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "升級硬體",
				Description:    "購買更高規格的伺服器",
				IsAWS:          false,
				OnPremSolution: "升級 CPU 和記憶體",
				Requirements:   ChoiceRequirements{MinCapital: 300, MinEmployees: 3, MinSecurityLevel: 1},
				Outcomes:       ChoiceOutcomes{CapitalChange: 100, EmployeeChange: 0, SecurityChange: 0, CloudAdoptionChange: -5, SuccessRate: 0.6, TimeToImplement: 2},
			},
		},
		AWSTopics: []string{"ElastiCache", "CloudFront", "X-Ray", "效能優化"},
	},
	{
		ID:           "challenge-002",
		Type:         EventChallenge,
		Title:        "資料庫擴展挑戰",
		Description:  "資料庫已達到效能極限，需要擴展方案",
		RealWorldRef: "Instagram 資料庫擴展",
		Context: EventContext{
			Scenario:       "單一資料庫已無法處理查詢負載",
			BusinessImpact: "查詢延遲影響用戶體驗",
			TechnicalNeeds: []string{"讀寫分離", "分片", "快取"},
			Constraints:    []string{"需保持資料一致性", "最小化停機時間"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "遷移到 Aurora",
				Description:  "使用 Aurora 的自動擴展和讀取副本功能",
				IsAWS:        true,
				AWSServices:  []string{"Aurora", "ElastiCache", "DMS"},
				Requirements: ChoiceRequirements{MinCapital: 200, MinEmployees: 6, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 250, EmployeeChange: 2, SecurityChange: 0, CloudAdoptionChange: 20, SuccessRate: 0.85, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "手動分片",
				Description:    "自行實作資料庫分片邏輯",
				IsAWS:          false,
				OnPremSolution: "使用 Vitess 或自建分片",
				Requirements:   ChoiceRequirements{MinCapital: 150, MinEmployees: 10, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 150, EmployeeChange: 0, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.6, TimeToImplement: 4},
			},
		},
		AWSTopics: []string{"Aurora", "RDS", "資料庫擴展", "讀取副本"},
	},
	{
		ID:           "challenge-003",
		Type:         EventChallenge,
		Title:        "API 整合挑戰",
		Description:  "需要整合多個第三方 API，但各有不同格式和限制",
		RealWorldRef: "金融科技 API 整合",
		Context: EventContext{
			Scenario:       "需要整合5個不同的支付和銀行 API",
			BusinessImpact: "整合成功可提供完整金融服務",
			TechnicalNeeds: []string{"API 閘道", "格式轉換", "錯誤處理"},
			Constraints:    []string{"各 API 有不同的速率限制", "需處理各種錯誤情況"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS API Gateway",
				Description:  "利用 API Gateway 和 Lambda 建立統一整合層",
				IsAWS:        true,
				AWSServices:  []string{"API Gateway", "Lambda", "Step Functions"},
				Requirements: ChoiceRequirements{MinCapital: 100, MinEmployees: 5, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 300, EmployeeChange: 3, SecurityChange: 1, CloudAdoptionChange: 15, SuccessRate: 0.8, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "自建整合層",
				Description:    "使用 Kong 或自建 API 閘道",
				IsAWS:          false,
				OnPremSolution: "部署 Kong API Gateway",
				Requirements:   ChoiceRequirements{MinCapital: 150, MinEmployees: 8, MinSecurityLevel: 3},
				Outcomes:       ChoiceOutcomes{CapitalChange: 200, EmployeeChange: 2, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.65, TimeToImplement: 3},
			},
		},
		AWSTopics: []string{"API Gateway", "Lambda", "Step Functions", "API 整合"},
	},
	{
		ID:           "challenge-004",
		Type:         EventChallenge,
		Title:        "即時資料處理",
		Description:  "需要處理大量即時資料流",
		RealWorldRef: "Uber 即時定價系統",
		Context: EventContext{
			Scenario:       "每秒需處理10萬筆事件資料",
			BusinessImpact: "即時分析可提升決策品質",
			TechnicalNeeds: []string{"串流處理", "即時分析", "資料儲存"},
			Constraints:    []string{"延遲需低於1秒", "不能遺失資料"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS Kinesis",
				Description:  "建立 Kinesis Data Streams + Lambda 即時處理管道",
				IsAWS:        true,
				AWSServices:  []string{"Kinesis", "Lambda", "DynamoDB"},
				Requirements: ChoiceRequirements{MinCapital: 250, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 350, EmployeeChange: 4, SecurityChange: 0, CloudAdoptionChange: 25, SuccessRate: 0.85, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "自建 Kafka 叢集",
				Description:    "部署 Apache Kafka 進行串流處理",
				IsAWS:          false,
				OnPremSolution: "建立 Kafka + Spark Streaming",
				Requirements:   ChoiceRequirements{MinCapital: 400, MinEmployees: 12, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 250, EmployeeChange: 3, SecurityChange: 0, CloudAdoptionChange: 5, SuccessRate: 0.65, TimeToImplement: 4},
			},
		},
		AWSTopics: []string{"Kinesis", "Lambda", "串流處理", "即時分析"},
	},
	{
		ID:           "challenge-005",
		Type:         EventChallenge,
		Title:        "多租戶架構",
		Description:  "需要將單租戶應用轉換為多租戶 SaaS",
		RealWorldRef: "Salesforce 多租戶架構",
		Context: EventContext{
			Scenario:       "客戶要求獨立的資料隔離和客製化",
			BusinessImpact: "多租戶可降低營運成本",
			TechnicalNeeds: []string{"資料隔離", "租戶管理", "計費系統"},
			Constraints:    []string{"需支援不同等級的隔離", "效能不能下降"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS SaaS 架構",
				Description:  "利用 Cognito、DynamoDB 和 Lambda 建立多租戶架構",
				IsAWS:        true,
				AWSServices:  []string{"Cognito", "DynamoDB", "Lambda", "API Gateway"},
				Requirements: ChoiceRequirements{MinCapital: 300, MinEmployees: 10, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 400, EmployeeChange: 5, SecurityChange: 1, CloudAdoptionChange: 30, SuccessRate: 0.75, TimeToImplement: 4},
			},
			{
				ID:             2,
				Title:          "每租戶獨立部署",
				Description:    "為每個租戶部署獨立環境",
				IsAWS:          false,
				OnPremSolution: "使用 Docker 容器隔離",
				Requirements:   ChoiceRequirements{MinCapital: 200, MinEmployees: 8, MinSecurityLevel: 3},
				Outcomes:       ChoiceOutcomes{CapitalChange: 250, EmployeeChange: 3, SecurityChange: 1, CloudAdoptionChange: 10, SuccessRate: 0.7, TimeToImplement: 3},
			},
		},
		AWSTopics: []string{"多租戶架構", "Cognito", "SaaS", "資料隔離"},
	},
	{
		ID:           "challenge-006",
		Type:         EventChallenge,
		Title:        "CI/CD 流程優化",
		Description:  "部署流程緩慢且容易出錯",
		RealWorldRef: "DevOps 轉型案例",
		Context: EventContext{
			Scenario:       "每次部署需要4小時，且經常失敗",
			BusinessImpact: "影響產品迭代速度",
			TechnicalNeeds: []string{"自動化部署", "測試自動化", "環境管理"},
			Constraints:    []string{"需支援多環境", "不能影響現有流程"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS DevOps 服務",
				Description:  "建立 CodePipeline + CodeBuild + CodeDeploy 流程",
				IsAWS:        true,
				AWSServices:  []string{"CodePipeline", "CodeBuild", "CodeDeploy", "ECR"},
				Requirements: ChoiceRequirements{MinCapital: 100, MinEmployees: 5, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 200, EmployeeChange: 2, SecurityChange: 1, CloudAdoptionChange: 20, SuccessRate: 0.85, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "自建 Jenkins 流程",
				Description:    "部署 Jenkins 並建立自動化流程",
				IsAWS:          false,
				OnPremSolution: "Jenkins + Ansible",
				Requirements:   ChoiceRequirements{MinCapital: 80, MinEmployees: 6, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 150, EmployeeChange: 1, SecurityChange: 0, CloudAdoptionChange: 5, SuccessRate: 0.7, TimeToImplement: 3},
			},
		},
		AWSTopics: []string{"CodePipeline", "CodeBuild", "CodeDeploy", "DevOps"},
	},
	{
		ID:           "challenge-007",
		Type:         EventChallenge,
		Title:        "日誌管理挑戰",
		Description:  "分散式系統的日誌難以追蹤和分析",
		RealWorldRef: "微服務可觀測性",
		Context: EventContext{
			Scenario:       "問題發生時需要數小時才能找到根因",
			BusinessImpact: "故障排除時間過長",
			TechnicalNeeds: []string{"集中式日誌", "搜尋分析", "告警通知"},
			Constraints:    []string{"日誌量大", "需保留90天"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 可觀測性服務",
				Description:  "部署 CloudWatch Logs、X-Ray 和 OpenSearch",
				IsAWS:        true,
				AWSServices:  []string{"CloudWatch", "X-Ray", "OpenSearch"},
				Requirements: ChoiceRequirements{MinCapital: 150, MinEmployees: 4, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 150, EmployeeChange: 1, SecurityChange: 1, CloudAdoptionChange: 15, SuccessRate: 0.85, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "自建 ELK Stack",
				Description:    "部署 Elasticsearch + Logstash + Kibana",
				IsAWS:          false,
				OnPremSolution: "自建 ELK 叢集",
				Requirements:   ChoiceRequirements{MinCapital: 200, MinEmployees: 6, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 100, EmployeeChange: 1, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.7, TimeToImplement: 3},
			},
		},
		AWSTopics: []string{"CloudWatch", "X-Ray", "OpenSearch", "可觀測性"},
	},

	// ==================== 資安事件 (Security) ====================
	{
		ID:           "sec-001",
		Type:         EventSecurity,
		Title:        "DDoS 攻擊",
		Description:  "網站遭受大規模 DDoS 攻擊",
		RealWorldRef: "2016 Dyn DNS 攻擊",
		Context: EventContext{
			Scenario:       "流量突然暴增100倍，服務無法存取",
			BusinessImpact: "服務中斷造成營收損失",
			TechnicalNeeds: []string{"流量清洗", "自動擴展", "攻擊緩解"},
			Constraints:    []string{"需立即處理", "不能影響正常用戶"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "啟用 AWS Shield Advanced",
				Description:  "使用 Shield Advanced 和 WAF 進行防護",
				IsAWS:        true,
				AWSServices:  []string{"AWS Shield", "AWS WAF", "CloudFront"},
				Requirements: ChoiceRequirements{MinCapital: 200, MinEmployees: 3, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 100, EmployeeChange: 0, SecurityChange: 2, CloudAdoptionChange: 10, SuccessRate: 0.95, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "聯繫 ISP 處理",
				Description:    "請求 ISP 協助過濾惡意流量",
				IsAWS:          false,
				OnPremSolution: "ISP 層級過濾",
				Requirements:   ChoiceRequirements{MinCapital: 100, MinEmployees: 2, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: -50, EmployeeChange: 0, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.6, TimeToImplement: 1},
			},
		},
		AWSTopics: []string{"AWS Shield", "AWS WAF", "DDoS 防護", "CloudFront"},
	},
	{
		ID:           "sec-002",
		Type:         EventSecurity,
		Title:        "資料外洩事件",
		Description:  "發現客戶資料可能已被未授權存取",
		RealWorldRef: "Equifax 資料外洩事件",
		Context: EventContext{
			Scenario:       "安全掃描發現資料庫有未授權存取記錄",
			BusinessImpact: "可能面臨法律訴訟和聲譽損失",
			TechnicalNeeds: []string{"事件調查", "漏洞修補", "通知受影響用戶"},
			Constraints:    []string{"需在24小時內通報主管機關", "需保留證據"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 安全服務調查",
				Description:  "利用 GuardDuty、Detective 和 Security Hub 進行調查",
				IsAWS:        true,
				AWSServices:  []string{"GuardDuty", "Detective", "Security Hub", "Macie"},
				Requirements: ChoiceRequirements{MinCapital: 150, MinEmployees: 5, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: -100, EmployeeChange: 0, SecurityChange: 2, CloudAdoptionChange: 15, SuccessRate: 0.85, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "聘請外部資安顧問",
				Description:    "委託專業資安公司進行調查",
				IsAWS:          false,
				OnPremSolution: "聘請資安鑑識公司",
				Requirements:   ChoiceRequirements{MinCapital: 300, MinEmployees: 3, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: -200, EmployeeChange: 0, SecurityChange: 1, CloudAdoptionChange: 0, SuccessRate: 0.75, TimeToImplement: 2},
			},
		},
		AWSTopics: []string{"GuardDuty", "Detective", "Security Hub", "資安事件回應"},
	},
	{
		ID:           "sec-003",
		Type:         EventSecurity,
		Title:        "勒索軟體攻擊",
		Description:  "公司伺服器遭勒索軟體加密",
		RealWorldRef: "WannaCry 勒索軟體事件",
		Context: EventContext{
			Scenario:       "多台伺服器檔案被加密，攻擊者要求比特幣贖金",
			BusinessImpact: "業務完全停擺",
			TechnicalNeeds: []string{"資料復原", "系統重建", "安全強化"},
			Constraints:    []string{"不建議支付贖金", "需盡快恢復服務"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "從 AWS 備份復原",
				Description:  "使用 AWS Backup 的異地備份進行復原",
				IsAWS:        true,
				AWSServices:  []string{"AWS Backup", "S3", "EC2 AMI"},
				Requirements: ChoiceRequirements{MinCapital: 100, MinEmployees: 5, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: -50, EmployeeChange: 0, SecurityChange: 2, CloudAdoptionChange: 20, SuccessRate: 0.9, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "從本地備份復原",
				Description:    "使用本地磁帶備份進行復原",
				IsAWS:          false,
				OnPremSolution: "磁帶備份復原",
				Requirements:   ChoiceRequirements{MinCapital: 50, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: -150, EmployeeChange: 0, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.5, TimeToImplement: 3},
			},
		},
		AWSTopics: []string{"AWS Backup", "災難復原", "資安事件回應"},
	},
	{
		ID:           "sec-004",
		Type:         EventSecurity,
		Title:        "API 金鑰外洩",
		Description:  "發現 API 金鑰被意外提交到公開 GitHub 儲存庫",
		RealWorldRef: "GitHub 金鑰外洩案例",
		Context: EventContext{
			Scenario:       "AWS Access Key 被推送到公開 repo，已被掃描機器人發現",
			BusinessImpact: "可能被用於未授權存取 AWS 資源",
			TechnicalNeeds: []string{"金鑰輪換", "存取審計", "權限檢查"},
			Constraints:    []string{"需立即處理", "不能中斷服務"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 安全最佳實踐",
				Description:  "停用金鑰、使用 IAM Role、啟用 CloudTrail 審計",
				IsAWS:        true,
				AWSServices:  []string{"IAM", "CloudTrail", "Secrets Manager"},
				Requirements: ChoiceRequirements{MinCapital: 50, MinEmployees: 3, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 50, EmployeeChange: 0, SecurityChange: 2, CloudAdoptionChange: 10, SuccessRate: 0.95, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "手動輪換金鑰",
				Description:    "手動更新所有使用該金鑰的服務",
				IsAWS:          false,
				OnPremSolution: "逐一更新設定檔",
				Requirements:   ChoiceRequirements{MinCapital: 20, MinEmployees: 5, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 0, EmployeeChange: 0, SecurityChange: 1, CloudAdoptionChange: 0, SuccessRate: 0.7, TimeToImplement: 1},
			},
		},
		AWSTopics: []string{"IAM", "Secrets Manager", "CloudTrail", "金鑰管理"},
	},
	{
		ID:           "sec-005",
		Type:         EventSecurity,
		Title:        "SQL 注入攻擊",
		Description:  "網站遭受 SQL 注入攻擊",
		RealWorldRef: "OWASP Top 10 - Injection",
		Context: EventContext{
			Scenario:       "WAF 日誌顯示大量 SQL 注入嘗試，部分可能成功",
			BusinessImpact: "資料庫資料可能被竊取或竄改",
			TechnicalNeeds: []string{"漏洞修補", "WAF 規則", "資料庫審計"},
			Constraints:    []string{"需立即阻擋攻擊", "需調查影響範圍"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "部署 AWS WAF 規則",
				Description:  "啟用 AWS WAF SQL 注入規則集並進行調查",
				IsAWS:        true,
				AWSServices:  []string{"AWS WAF", "CloudWatch", "RDS"},
				Requirements: ChoiceRequirements{MinCapital: 80, MinEmployees: 4, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 50, EmployeeChange: 0, SecurityChange: 2, CloudAdoptionChange: 10, SuccessRate: 0.9, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "緊急修補程式碼",
				Description:    "立即修補有漏洞的程式碼",
				IsAWS:          false,
				OnPremSolution: "程式碼審查和修補",
				Requirements:   ChoiceRequirements{MinCapital: 50, MinEmployees: 6, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 0, EmployeeChange: 0, SecurityChange: 1, CloudAdoptionChange: 0, SuccessRate: 0.75, TimeToImplement: 2},
			},
		},
		AWSTopics: []string{"AWS WAF", "SQL 注入", "Web 安全"},
	},
	{
		ID:           "sec-006",
		Type:         EventSecurity,
		Title:        "內部威脅",
		Description:  "發現員工可能在進行未授權的資料存取",
		RealWorldRef: "內部威脅案例",
		Context: EventContext{
			Scenario:       "離職員工帳號仍有存取權限，且有異常存取記錄",
			BusinessImpact: "敏感資料可能外洩",
			TechnicalNeeds: []string{"存取控制", "行為分析", "權限審計"},
			Constraints:    []string{"需保留證據", "不能打草驚蛇"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 安全監控",
				Description:  "利用 CloudTrail、GuardDuty 進行調查和監控",
				IsAWS:        true,
				AWSServices:  []string{"CloudTrail", "GuardDuty", "IAM Access Analyzer"},
				Requirements: ChoiceRequirements{MinCapital: 100, MinEmployees: 4, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 50, EmployeeChange: 0, SecurityChange: 2, CloudAdoptionChange: 10, SuccessRate: 0.85, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "立即停用帳號",
				Description:    "直接停用可疑帳號並進行調查",
				IsAWS:          false,
				OnPremSolution: "IT 部門手動處理",
				Requirements:   ChoiceRequirements{MinCapital: 30, MinEmployees: 3, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 0, EmployeeChange: 0, SecurityChange: 1, CloudAdoptionChange: 0, SuccessRate: 0.7, TimeToImplement: 1},
			},
		},
		AWSTopics: []string{"CloudTrail", "GuardDuty", "IAM", "內部威脅"},
	},
	{
		ID:           "sec-007",
		Type:         EventSecurity,
		Title:        "憑證遭竊",
		Description:  "員工收到釣魚郵件，可能已洩漏登入憑證",
		RealWorldRef: "釣魚攻擊案例",
		Context: EventContext{
			Scenario:       "多名員工回報收到偽造的密碼重設郵件",
			BusinessImpact: "帳號可能被盜用",
			TechnicalNeeds: []string{"密碼重設", "MFA 啟用", "安全意識訓練"},
			Constraints:    []string{"需快速反應", "不能影響正常工作"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "強制啟用 AWS MFA",
				Description:  "為所有 IAM 用戶啟用 MFA，並使用 Cognito 加強認證",
				IsAWS:        true,
				AWSServices:  []string{"IAM MFA", "Cognito", "SES"},
				Requirements: ChoiceRequirements{MinCapital: 50, MinEmployees: 3, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 30, EmployeeChange: 0, SecurityChange: 2, CloudAdoptionChange: 5, SuccessRate: 0.9, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "全面密碼重設",
				Description:    "強制所有員工重設密碼",
				IsAWS:          false,
				OnPremSolution: "AD 密碼重設",
				Requirements:   ChoiceRequirements{MinCapital: 20, MinEmployees: 5, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 0, EmployeeChange: 0, SecurityChange: 1, CloudAdoptionChange: 0, SuccessRate: 0.75, TimeToImplement: 1},
			},
		},
		AWSTopics: []string{"IAM MFA", "Cognito", "身份認證", "釣魚防護"},
	},
	{
		ID:           "sec-008",
		Type:         EventSecurity,
		Title:        "零日漏洞",
		Description:  "使用的開源套件發現嚴重零日漏洞",
		RealWorldRef: "Log4j 漏洞事件",
		Context: EventContext{
			Scenario:       "廣泛使用的 Log4j 套件發現遠端程式碼執行漏洞",
			BusinessImpact: "系統可能被完全控制",
			TechnicalNeeds: []string{"漏洞掃描", "緊急修補", "WAF 防護"},
			Constraints:    []string{"需立即處理", "修補可能影響穩定性"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 安全服務防護",
				Description:  "部署 WAF 規則阻擋攻擊，使用 Inspector 掃描漏洞",
				IsAWS:        true,
				AWSServices:  []string{"AWS WAF", "Inspector", "Systems Manager"},
				Requirements: ChoiceRequirements{MinCapital: 100, MinEmployees: 5, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 50, EmployeeChange: 0, SecurityChange: 2, CloudAdoptionChange: 15, SuccessRate: 0.9, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "緊急更新套件",
				Description:    "立即更新所有受影響的套件版本",
				IsAWS:          false,
				OnPremSolution: "手動更新和測試",
				Requirements:   ChoiceRequirements{MinCapital: 50, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 0, EmployeeChange: 0, SecurityChange: 1, CloudAdoptionChange: 0, SuccessRate: 0.7, TimeToImplement: 2},
			},
		},
		AWSTopics: []string{"AWS WAF", "Inspector", "漏洞管理", "零日攻擊"},
	},
	// ==================== 更多機會事件 ====================
	{
		ID:           "opp-011",
		Type:         EventOpportunity,
		Title:        "政府標案機會",
		Description:  "政府機關公開招標雲端服務專案",
		RealWorldRef: "政府雲端採購案例",
		Context: EventContext{
			Scenario:       "標案金額達5000萬，需要符合政府資安規範",
			BusinessImpact: "中標可帶來穩定營收",
			TechnicalNeeds: []string{"資安認證", "在地化部署", "合規報告"},
			Constraints:    []string{"需符合政府雲端規範", "需有相關經驗"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS GovCloud 架構",
				Description:  "利用 AWS 政府雲端合規架構投標",
				IsAWS:        true,
				AWSServices:  []string{"AWS GovCloud", "CloudTrail", "Config"},
				Requirements: ChoiceRequirements{MinCapital: 300, MinEmployees: 15, MinSecurityLevel: 4},
				Outcomes:     ChoiceOutcomes{CapitalChange: 1000, EmployeeChange: 20, SecurityChange: 2, CloudAdoptionChange: 20, SuccessRate: 0.6, TimeToImplement: 4},
			},
			{
				ID:             2,
				Title:          "與本地 IDC 合作投標",
				Description:    "與本地資料中心合作提案",
				IsAWS:          false,
				OnPremSolution: "本地機房 + 自建系統",
				Requirements:   ChoiceRequirements{MinCapital: 500, MinEmployees: 20, MinSecurityLevel: 4},
				Outcomes:       ChoiceOutcomes{CapitalChange: 800, EmployeeChange: 15, SecurityChange: 1, CloudAdoptionChange: -5, SuccessRate: 0.5, TimeToImplement: 5},
			},
		},
		AWSTopics: []string{"政府雲端", "合規性", "CloudTrail"},
	},
	{
		ID:           "opp-012",
		Type:         EventOpportunity,
		Title:        "串流媒體服務",
		Description:  "公司決定推出影音串流服務",
		RealWorldRef: "Disney+ 串流服務",
		Context: EventContext{
			Scenario:       "內容授權已談妥，需要建立串流平台",
			BusinessImpact: "可開拓訂閱制營收",
			TechnicalNeeds: []string{"影音轉碼", "CDN 分發", "DRM 保護"},
			Constraints:    []string{"需支援多種裝置", "全球低延遲"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 媒體服務",
				Description:  "建立 MediaConvert + CloudFront + Elemental 串流平台",
				IsAWS:        true,
				AWSServices:  []string{"MediaConvert", "CloudFront", "Elemental", "S3"},
				Requirements: ChoiceRequirements{MinCapital: 400, MinEmployees: 12, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 600, EmployeeChange: 10, SecurityChange: 1, CloudAdoptionChange: 25, SuccessRate: 0.8, TimeToImplement: 3},
			},
			{
				ID:             2,
				Title:          "自建串流平台",
				Description:    "使用開源方案自建串流系統",
				IsAWS:          false,
				OnPremSolution: "FFmpeg + Nginx RTMP",
				Requirements:   ChoiceRequirements{MinCapital: 600, MinEmployees: 18, MinSecurityLevel: 3},
				Outcomes:       ChoiceOutcomes{CapitalChange: 400, EmployeeChange: 8, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.55, TimeToImplement: 6},
			},
		},
		AWSTopics: []string{"MediaConvert", "CloudFront", "串流媒體", "CDN"},
	},
	{
		ID:           "opp-013",
		Type:         EventOpportunity,
		Title:        "遊戲後端服務",
		Description:  "遊戲開發團隊需要建立多人連線後端",
		RealWorldRef: "Fortnite 後端架構",
		Context: EventContext{
			Scenario:       "新遊戲預計同時在線人數達10萬",
			BusinessImpact: "遊戲體驗直接影響營收",
			TechnicalNeeds: []string{"即時連線", "配對系統", "排行榜"},
			Constraints:    []string{"延遲需低於100ms", "需支援全球玩家"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 遊戲服務",
				Description:  "部署 GameLift + DynamoDB + ElastiCache",
				IsAWS:        true,
				AWSServices:  []string{"GameLift", "DynamoDB", "ElastiCache", "API Gateway"},
				Requirements: ChoiceRequirements{MinCapital: 350, MinEmployees: 10, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 500, EmployeeChange: 8, SecurityChange: 0, CloudAdoptionChange: 25, SuccessRate: 0.8, TimeToImplement: 3},
			},
			{
				ID:             2,
				Title:          "自建遊戲伺服器",
				Description:    "租用專用伺服器自建後端",
				IsAWS:          false,
				OnPremSolution: "專用遊戲伺服器",
				Requirements:   ChoiceRequirements{MinCapital: 500, MinEmployees: 15, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 350, EmployeeChange: 5, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.6, TimeToImplement: 5},
			},
		},
		AWSTopics: []string{"GameLift", "DynamoDB", "遊戲後端", "即時連線"},
	},

	// ==================== 更多命運事件 ====================
	{
		ID:           "fate-009",
		Type:         EventFate,
		Title:        "疫情影響",
		Description:  "全球疫情導致遠端工作需求激增",
		RealWorldRef: "COVID-19 數位轉型",
		Context: EventContext{
			Scenario:       "員工需要在家工作，客戶也轉向線上服務",
			BusinessImpact: "需要快速調整營運模式",
			TechnicalNeeds: []string{"遠端存取", "協作工具", "VPN 擴展"},
			Constraints:    []string{"需在一週內完成", "預算有限"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS WorkSpaces",
				Description:  "部署 WorkSpaces 和 Client VPN 支援遠端工作",
				IsAWS:        true,
				AWSServices:  []string{"WorkSpaces", "Client VPN", "Directory Service"},
				Requirements: ChoiceRequirements{MinCapital: 150, MinEmployees: 5, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 200, EmployeeChange: 0, SecurityChange: 1, CloudAdoptionChange: 20, SuccessRate: 0.9, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "擴展現有 VPN",
				Description:    "增加 VPN 授權和頻寬",
				IsAWS:          false,
				OnPremSolution: "擴展 Cisco VPN",
				Requirements:   ChoiceRequirements{MinCapital: 200, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 100, EmployeeChange: 0, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.7, TimeToImplement: 2},
			},
		},
		AWSTopics: []string{"WorkSpaces", "Client VPN", "遠端工作"},
	},
	{
		ID:           "fate-010",
		Type:         EventFate,
		Title:        "匯率波動",
		Description:  "美元大幅升值，雲端成本增加",
		RealWorldRef: "匯率風險管理",
		Context: EventContext{
			Scenario:       "美元升值20%，AWS 帳單大幅增加",
			BusinessImpact: "IT 預算超支",
			TechnicalNeeds: []string{"成本優化", "資源調整", "預算控制"},
			Constraints:    []string{"不能影響服務品質", "需立即見效"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "優化 AWS 使用",
				Description:  "使用 Savings Plans、Spot Instances 和 Reserved Instances",
				IsAWS:        true,
				AWSServices:  []string{"Savings Plans", "Spot Instances", "Cost Explorer"},
				Requirements: ChoiceRequirements{MinCapital: 50, MinEmployees: 3, MinSecurityLevel: 1},
				Outcomes:     ChoiceOutcomes{CapitalChange: 150, EmployeeChange: 0, SecurityChange: 0, CloudAdoptionChange: 5, SuccessRate: 0.85, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "遷回本地機房",
				Description:    "將部分工作負載遷回本地以降低成本",
				IsAWS:          false,
				OnPremSolution: "混合雲架構",
				Requirements:   ChoiceRequirements{MinCapital: 300, MinEmployees: 10, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 100, EmployeeChange: 2, SecurityChange: 0, CloudAdoptionChange: -15, SuccessRate: 0.6, TimeToImplement: 3},
			},
		},
		AWSTopics: []string{"Savings Plans", "Spot Instances", "成本優化"},
	},

	// ==================== 更多關卡事件 ====================
	{
		ID:           "challenge-008",
		Type:         EventChallenge,
		Title:        "無伺服器轉型",
		Description:  "需要將傳統應用轉換為無伺服器架構",
		RealWorldRef: "Serverless 轉型案例",
		Context: EventContext{
			Scenario:       "維護成本過高，希望轉向按需付費模式",
			BusinessImpact: "可大幅降低營運成本",
			TechnicalNeeds: []string{"函數拆分", "事件驅動", "狀態管理"},
			Constraints:    []string{"需保持 API 相容", "冷啟動時間限制"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS Lambda",
				Description:  "將應用重構為 Lambda + API Gateway + DynamoDB",
				IsAWS:        true,
				AWSServices:  []string{"Lambda", "API Gateway", "DynamoDB", "Step Functions"},
				Requirements: ChoiceRequirements{MinCapital: 200, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 300, EmployeeChange: 3, SecurityChange: 1, CloudAdoptionChange: 30, SuccessRate: 0.75, TimeToImplement: 3},
			},
			{
				ID:             2,
				Title:          "容器化現有應用",
				Description:    "將應用容器化但保持架構不變",
				IsAWS:          false,
				OnPremSolution: "Docker + Kubernetes",
				Requirements:   ChoiceRequirements{MinCapital: 150, MinEmployees: 6, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 200, EmployeeChange: 2, SecurityChange: 0, CloudAdoptionChange: 15, SuccessRate: 0.8, TimeToImplement: 2},
			},
		},
		AWSTopics: []string{"Lambda", "API Gateway", "Serverless", "Step Functions"},
	},
	{
		ID:           "challenge-009",
		Type:         EventChallenge,
		Title:        "全文搜尋功能",
		Description:  "需要為產品加入全文搜尋功能",
		RealWorldRef: "電商搜尋優化",
		Context: EventContext{
			Scenario:       "用戶抱怨搜尋結果不準確，需要改善搜尋體驗",
			BusinessImpact: "搜尋品質直接影響轉換率",
			TechnicalNeeds: []string{"全文索引", "相關性排序", "自動完成"},
			Constraints:    []string{"需支援中文", "搜尋延遲低於200ms"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS OpenSearch",
				Description:  "部署 OpenSearch Service 建立搜尋引擎",
				IsAWS:        true,
				AWSServices:  []string{"OpenSearch", "Lambda", "API Gateway"},
				Requirements: ChoiceRequirements{MinCapital: 150, MinEmployees: 5, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 200, EmployeeChange: 2, SecurityChange: 0, CloudAdoptionChange: 15, SuccessRate: 0.85, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "自建 Elasticsearch",
				Description:    "自行部署和管理 Elasticsearch 叢集",
				IsAWS:          false,
				OnPremSolution: "自建 Elasticsearch",
				Requirements:   ChoiceRequirements{MinCapital: 200, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 150, EmployeeChange: 1, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.7, TimeToImplement: 3},
			},
		},
		AWSTopics: []string{"OpenSearch", "全文搜尋", "Elasticsearch"},
	},
	{
		ID:           "challenge-010",
		Type:         EventChallenge,
		Title:        "訊息佇列架構",
		Description:  "需要實作非同步處理以提升系統彈性",
		RealWorldRef: "微服務訊息架構",
		Context: EventContext{
			Scenario:       "同步處理導致系統耦合度高，故障會連鎖反應",
			BusinessImpact: "系統穩定性需要提升",
			TechnicalNeeds: []string{"訊息佇列", "非同步處理", "重試機制"},
			Constraints:    []string{"需保證訊息不遺失", "需支援高吞吐量"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS SQS/SNS",
				Description:  "部署 SQS + SNS + Lambda 建立事件驅動架構",
				IsAWS:        true,
				AWSServices:  []string{"SQS", "SNS", "Lambda", "EventBridge"},
				Requirements: ChoiceRequirements{MinCapital: 100, MinEmployees: 5, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 200, EmployeeChange: 2, SecurityChange: 0, CloudAdoptionChange: 20, SuccessRate: 0.85, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "自建 RabbitMQ",
				Description:    "部署 RabbitMQ 叢集",
				IsAWS:          false,
				OnPremSolution: "RabbitMQ 叢集",
				Requirements:   ChoiceRequirements{MinCapital: 150, MinEmployees: 6, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 150, EmployeeChange: 1, SecurityChange: 0, CloudAdoptionChange: 5, SuccessRate: 0.7, TimeToImplement: 3},
			},
		},
		AWSTopics: []string{"SQS", "SNS", "EventBridge", "訊息佇列"},
	},

	// ==================== 額外事件以達到50個 ====================
	{
		ID:           "opp-014",
		Type:         EventOpportunity,
		Title:        "區塊鏈應用",
		Description:  "客戶要求建立區塊鏈追溯系統",
		RealWorldRef: "供應鏈區塊鏈案例",
		Context: EventContext{
			Scenario:       "食品業客戶需要產品溯源功能",
			BusinessImpact: "可開拓新的業務領域",
			TechnicalNeeds: []string{"區塊鏈網路", "智能合約", "API 整合"},
			Constraints:    []string{"需符合食品安全法規", "交易確認時間限制"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS Managed Blockchain",
				Description:  "部署 Amazon Managed Blockchain 建立私有鏈",
				IsAWS:        true,
				AWSServices:  []string{"Managed Blockchain", "Lambda", "API Gateway"},
				Requirements: ChoiceRequirements{MinCapital: 300, MinEmployees: 8, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 400, EmployeeChange: 5, SecurityChange: 1, CloudAdoptionChange: 20, SuccessRate: 0.7, TimeToImplement: 4},
			},
			{
				ID:             2,
				Title:          "自建 Hyperledger",
				Description:    "自行部署 Hyperledger Fabric 網路",
				IsAWS:          false,
				OnPremSolution: "Hyperledger Fabric",
				Requirements:   ChoiceRequirements{MinCapital: 400, MinEmployees: 12, MinSecurityLevel: 3},
				Outcomes:       ChoiceOutcomes{CapitalChange: 300, EmployeeChange: 4, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.55, TimeToImplement: 6},
			},
		},
		AWSTopics: []string{"Managed Blockchain", "區塊鏈", "Hyperledger"},
	},
	{
		ID:           "opp-015",
		Type:         EventOpportunity,
		Title:        "邊緣運算部署",
		Description:  "工廠客戶需要低延遲的邊緣運算解決方案",
		RealWorldRef: "工業4.0邊緣運算",
		Context: EventContext{
			Scenario:       "製造業客戶需要即時品質檢測",
			BusinessImpact: "可進入工業物聯網市場",
			TechnicalNeeds: []string{"邊緣裝置", "ML推論", "資料同步"},
			Constraints:    []string{"延遲需低於10ms", "需離線運作能力"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS IoT Greengrass",
				Description:  "部署 Greengrass 進行邊緣運算和 ML 推論",
				IsAWS:        true,
				AWSServices:  []string{"IoT Greengrass", "SageMaker Edge", "IoT Core"},
				Requirements: ChoiceRequirements{MinCapital: 250, MinEmployees: 8, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 350, EmployeeChange: 6, SecurityChange: 1, CloudAdoptionChange: 20, SuccessRate: 0.75, TimeToImplement: 3},
			},
			{
				ID:             2,
				Title:          "自建邊緣系統",
				Description:    "使用工業電腦自建邊緣運算系統",
				IsAWS:          false,
				OnPremSolution: "工業電腦 + 自建軟體",
				Requirements:   ChoiceRequirements{MinCapital: 350, MinEmployees: 12, MinSecurityLevel: 3},
				Outcomes:       ChoiceOutcomes{CapitalChange: 250, EmployeeChange: 4, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.6, TimeToImplement: 5},
			},
		},
		AWSTopics: []string{"IoT Greengrass", "邊緣運算", "SageMaker Edge"},
	},
	{
		ID:           "fate-011",
		Type:         EventFate,
		Title:        "雲端服務中斷",
		Description:  "主要雲端區域發生服務中斷",
		RealWorldRef: "AWS us-east-1 中斷事件",
		Context: EventContext{
			Scenario:       "依賴的雲端區域發生大規模中斷",
			BusinessImpact: "服務無法存取，客戶抱怨",
			TechnicalNeeds: []string{"多區域部署", "故障轉移", "監控告警"},
			Constraints:    []string{"需快速恢復", "預算有限"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "啟用多區域架構",
				Description:  "將服務部署到多個 AWS 區域",
				IsAWS:        true,
				AWSServices:  []string{"Route 53", "Global Accelerator", "S3 Cross-Region"},
				Requirements: ChoiceRequirements{MinCapital: 200, MinEmployees: 5, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 100, EmployeeChange: 1, SecurityChange: 1, CloudAdoptionChange: 15, SuccessRate: 0.85, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "等待服務恢復",
				Description:    "等待雲端供應商修復問題",
				IsAWS:          false,
				OnPremSolution: "被動等待",
				Requirements:   ChoiceRequirements{MinCapital: 0, MinEmployees: 1, MinSecurityLevel: 1},
				Outcomes:       ChoiceOutcomes{CapitalChange: -150, EmployeeChange: 0, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.5, TimeToImplement: 1},
			},
		},
		AWSTopics: []string{"多區域架構", "Route 53", "高可用性"},
	},
	{
		ID:           "fate-012",
		Type:         EventFate,
		Title:        "開源專案停止維護",
		Description:  "核心依賴的開源專案宣布停止維護",
		RealWorldRef: "開源專案生命週期",
		Context: EventContext{
			Scenario:       "使用的關鍵開源框架不再更新",
			BusinessImpact: "安全風險增加，需要遷移",
			TechnicalNeeds: []string{"框架遷移", "相容性測試", "程式碼重構"},
			Constraints:    []string{"需保持功能相容", "時間有限"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "遷移到 AWS 託管服務",
				Description:  "將依賴遷移到 AWS 託管的替代方案",
				IsAWS:        true,
				AWSServices:  []string{"Lambda", "ECS", "RDS"},
				Requirements: ChoiceRequirements{MinCapital: 150, MinEmployees: 6, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 100, EmployeeChange: 1, SecurityChange: 1, CloudAdoptionChange: 15, SuccessRate: 0.8, TimeToImplement: 3},
			},
			{
				ID:             2,
				Title:          "Fork 並自行維護",
				Description:    "Fork 開源專案並自行維護",
				IsAWS:          false,
				OnPremSolution: "自行維護 Fork",
				Requirements:   ChoiceRequirements{MinCapital: 100, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 50, EmployeeChange: 2, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.6, TimeToImplement: 2},
			},
		},
		AWSTopics: []string{"系統現代化", "遷移策略"},
	},
	{
		ID:           "challenge-011",
		Type:         EventChallenge,
		Title:        "GraphQL API 設計",
		Description:  "需要為行動應用設計高效的 API",
		RealWorldRef: "Facebook GraphQL",
		Context: EventContext{
			Scenario:       "REST API 造成過多請求，影響行動應用效能",
			BusinessImpact: "用戶體驗需要改善",
			TechnicalNeeds: []string{"GraphQL 設計", "查詢優化", "快取策略"},
			Constraints:    []string{"需相容現有 REST API", "學習曲線"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS AppSync",
				Description:  "部署 AppSync 建立 GraphQL API",
				IsAWS:        true,
				AWSServices:  []string{"AppSync", "DynamoDB", "Lambda"},
				Requirements: ChoiceRequirements{MinCapital: 100, MinEmployees: 5, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 200, EmployeeChange: 2, SecurityChange: 0, CloudAdoptionChange: 15, SuccessRate: 0.85, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "自建 GraphQL 伺服器",
				Description:    "使用 Apollo Server 自建 GraphQL",
				IsAWS:          false,
				OnPremSolution: "Apollo Server",
				Requirements:   ChoiceRequirements{MinCapital: 80, MinEmployees: 6, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 150, EmployeeChange: 1, SecurityChange: 0, CloudAdoptionChange: 5, SuccessRate: 0.75, TimeToImplement: 3},
			},
		},
		AWSTopics: []string{"AppSync", "GraphQL", "API 設計"},
	},
	{
		ID:           "challenge-012",
		Type:         EventChallenge,
		Title:        "密碼管理系統",
		Description:  "需要建立安全的密碼和憑證管理系統",
		RealWorldRef: "DevSecOps 最佳實踐",
		Context: EventContext{
			Scenario:       "密碼散落在程式碼和設定檔中",
			BusinessImpact: "安全風險高，需要集中管理",
			TechnicalNeeds: []string{"密碼輪換", "存取控制", "稽核日誌"},
			Constraints:    []string{"需支援多種應用", "不能中斷服務"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS Secrets Manager",
				Description:  "部署 Secrets Manager 集中管理密碼",
				IsAWS:        true,
				AWSServices:  []string{"Secrets Manager", "IAM", "CloudTrail"},
				Requirements: ChoiceRequirements{MinCapital: 80, MinEmployees: 4, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 100, EmployeeChange: 1, SecurityChange: 2, CloudAdoptionChange: 10, SuccessRate: 0.9, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "部署 HashiCorp Vault",
				Description:    "自建 Vault 叢集管理密碼",
				IsAWS:          false,
				OnPremSolution: "HashiCorp Vault",
				Requirements:   ChoiceRequirements{MinCapital: 120, MinEmployees: 6, MinSecurityLevel: 3},
				Outcomes:       ChoiceOutcomes{CapitalChange: 80, EmployeeChange: 1, SecurityChange: 2, CloudAdoptionChange: 0, SuccessRate: 0.75, TimeToImplement: 2},
			},
		},
		AWSTopics: []string{"Secrets Manager", "密碼管理", "DevSecOps"},
	},
	{
		ID:           "sec-009",
		Type:         EventSecurity,
		Title:        "加密貨幣挖礦攻擊",
		Description:  "發現伺服器被植入加密貨幣挖礦程式",
		RealWorldRef: "雲端挖礦攻擊案例",
		Context: EventContext{
			Scenario:       "AWS 帳單異常增加，發現有未知 EC2 實例",
			BusinessImpact: "成本大幅增加，可能有其他入侵",
			TechnicalNeeds: []string{"入侵調查", "帳號安全", "成本控制"},
			Constraints:    []string{"需立即處理", "需找出入侵途徑"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 安全服務調查",
				Description:  "利用 GuardDuty、Detective 調查並加強 IAM 安全",
				IsAWS:        true,
				AWSServices:  []string{"GuardDuty", "Detective", "IAM", "Budgets"},
				Requirements: ChoiceRequirements{MinCapital: 100, MinEmployees: 4, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 50, EmployeeChange: 0, SecurityChange: 2, CloudAdoptionChange: 10, SuccessRate: 0.9, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "關閉所有可疑資源",
				Description:    "立即終止所有可疑的運算資源",
				IsAWS:          false,
				OnPremSolution: "手動清理",
				Requirements:   ChoiceRequirements{MinCapital: 50, MinEmployees: 3, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: -50, EmployeeChange: 0, SecurityChange: 1, CloudAdoptionChange: 0, SuccessRate: 0.7, TimeToImplement: 1},
			},
		},
		AWSTopics: []string{"GuardDuty", "IAM", "成本管理", "入侵偵測"},
	},
	{
		ID:           "sec-010",
		Type:         EventSecurity,
		Title:        "供應鏈攻擊",
		Description:  "使用的第三方套件被發現含有惡意程式碼",
		RealWorldRef: "SolarWinds 供應鏈攻擊",
		Context: EventContext{
			Scenario:       "NPM 套件被發現含有後門程式",
			BusinessImpact: "系統可能已被入侵",
			TechnicalNeeds: []string{"套件審計", "漏洞掃描", "程式碼審查"},
			Constraints:    []string{"需快速評估影響", "需更新所有環境"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 安全掃描",
				Description:  "利用 Inspector、CodeGuru 掃描並修復漏洞",
				IsAWS:        true,
				AWSServices:  []string{"Inspector", "CodeGuru", "ECR Scanning"},
				Requirements: ChoiceRequirements{MinCapital: 100, MinEmployees: 5, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 50, EmployeeChange: 0, SecurityChange: 2, CloudAdoptionChange: 10, SuccessRate: 0.85, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "手動審計和更新",
				Description:    "手動檢查所有依賴並更新",
				IsAWS:          false,
				OnPremSolution: "手動審計",
				Requirements:   ChoiceRequirements{MinCapital: 50, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 0, EmployeeChange: 0, SecurityChange: 1, CloudAdoptionChange: 0, SuccessRate: 0.7, TimeToImplement: 2},
			},
		},
		AWSTopics: []string{"Inspector", "CodeGuru", "供應鏈安全"},
	},
	{
		ID:           "opp-016",
		Type:         EventOpportunity,
		Title:        "語音助理整合",
		Description:  "客戶要求整合語音助理功能",
		RealWorldRef: "Alexa Skills 開發",
		Context: EventContext{
			Scenario:       "客戶希望透過語音控制應用功能",
			BusinessImpact: "可提升用戶體驗和黏著度",
			TechnicalNeeds: []string{"語音識別", "自然語言處理", "API 整合"},
			Constraints:    []string{"需支援多種語言", "回應時間限制"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS AI 服務",
				Description:  "整合 Lex、Polly、Transcribe 建立語音功能",
				IsAWS:        true,
				AWSServices:  []string{"Lex", "Polly", "Transcribe", "Lambda"},
				Requirements: ChoiceRequirements{MinCapital: 150, MinEmployees: 5, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 250, EmployeeChange: 3, SecurityChange: 0, CloudAdoptionChange: 15, SuccessRate: 0.8, TimeToImplement: 2},
			},
			{
				ID:             2,
				Title:          "使用開源語音方案",
				Description:    "整合開源語音識別引擎",
				IsAWS:          false,
				OnPremSolution: "Mozilla DeepSpeech",
				Requirements:   ChoiceRequirements{MinCapital: 200, MinEmployees: 8, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 180, EmployeeChange: 2, SecurityChange: 0, CloudAdoptionChange: 0, SuccessRate: 0.6, TimeToImplement: 4},
			},
		},
		AWSTopics: []string{"Lex", "Polly", "Transcribe", "語音 AI"},
	},
	// ==================== 額外資安事件 ====================
	{
		ID:           "sec-011",
		Type:         EventSecurity,
		Title:        "雲端設定錯誤",
		Description:  "發現 S3 儲存桶設定為公開存取",
		RealWorldRef: "Capital One 資料外洩事件",
		Context: EventContext{
			Scenario:       "安全掃描發現多個 S3 儲存桶設定為公開",
			BusinessImpact: "敏感資料可能已被存取",
			TechnicalNeeds: []string{"存取控制", "設定審計", "資料分類"},
			Constraints:    []string{"需立即修復", "需評估影響範圍"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 安全服務修復",
				Description:  "利用 Config Rules、Access Analyzer 和 Macie 進行修復和監控",
				IsAWS:        true,
				AWSServices:  []string{"AWS Config", "IAM Access Analyzer", "Macie", "S3"},
				Requirements: ChoiceRequirements{MinCapital: 80, MinEmployees: 4, MinSecurityLevel: 3},
				Outcomes:     ChoiceOutcomes{CapitalChange: 50, EmployeeChange: 0, SecurityChange: 2, CloudAdoptionChange: 10, SuccessRate: 0.9, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "手動修復設定",
				Description:    "逐一檢查並修復所有儲存桶設定",
				IsAWS:          false,
				OnPremSolution: "手動審計和修復",
				Requirements:   ChoiceRequirements{MinCapital: 50, MinEmployees: 6, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: 0, EmployeeChange: 0, SecurityChange: 1, CloudAdoptionChange: 0, SuccessRate: 0.7, TimeToImplement: 2},
			},
		},
		AWSTopics: []string{"S3 安全", "AWS Config", "IAM Access Analyzer", "雲端設定"},
	},
	{
		ID:           "sec-012",
		Type:         EventSecurity,
		Title:        "帳號遭盜用",
		Description:  "發現 AWS 帳號有異常的高額費用",
		RealWorldRef: "AWS 帳號盜用案例",
		Context: EventContext{
			Scenario:       "帳單顯示異常的 EC2 和 Lambda 使用量",
			BusinessImpact: "可能產生大量未預期費用",
			TechnicalNeeds: []string{"帳號安全", "費用監控", "存取審計"},
			Constraints:    []string{"需立即處理", "需找出入侵途徑"},
		},
		Choices: []EventChoice{
			{
				ID:           1,
				Title:        "使用 AWS 安全最佳實踐",
				Description:  "啟用 MFA、輪換金鑰、設定 Budgets 告警",
				IsAWS:        true,
				AWSServices:  []string{"IAM", "AWS Budgets", "CloudTrail", "GuardDuty"},
				Requirements: ChoiceRequirements{MinCapital: 50, MinEmployees: 3, MinSecurityLevel: 2},
				Outcomes:     ChoiceOutcomes{CapitalChange: 30, EmployeeChange: 0, SecurityChange: 2, CloudAdoptionChange: 5, SuccessRate: 0.9, TimeToImplement: 1},
			},
			{
				ID:             2,
				Title:          "聯繫 AWS 支援",
				Description:    "開立支援案件請求協助調查",
				IsAWS:          false,
				OnPremSolution: "AWS Support 協助",
				Requirements:   ChoiceRequirements{MinCapital: 30, MinEmployees: 2, MinSecurityLevel: 2},
				Outcomes:       ChoiceOutcomes{CapitalChange: -20, EmployeeChange: 0, SecurityChange: 1, CloudAdoptionChange: 0, SuccessRate: 0.8, TimeToImplement: 1},
			},
		},
		AWSTopics: []string{"IAM 安全", "AWS Budgets", "帳號安全", "成本管理"},
	},
}

// GetDefaultEventSystem 取得包含預設事件的事件系統
func GetDefaultEventSystem() EventSystem {
	return NewEventSystemWithEvents(DefaultEvents)
}
